### PR TITLE
Share claims with gossiped peers

### LINKED ISSUE #7: Put claim chain reference and keyhandle in claim rather than keydata
Currently we still have the entire OpenPGP keydata in the claim.
Replace this with a dict of root-hash, store-url and OpenPGP fingerprint.

That way chains can be retrieved based on the claim and the recipient can lookup the pks for the other recipients.

### LINKED ISSUE #8: retrieve peer claim chains when seeing them in gossip
This way we canget hold of their pks and also encrypt claims to them.

blocked by #7

### PR DESCRIPTION
**Pull request by azul**
use gossiped cc info to share claims in replies

We achieve this by registering peers based on gossip.
However currently this will overwrite their cc info without
checking for consistency. (#13)

fixes #7 
fixes #8

### CODE REVIEW

**Comment by azul** [comment]
tests are failing because this depends on hpk42/muacrypt#66

**Comment by azul** [comment]
Interesting... the push test seem to be failing because of issues with claim integrity:
```
    def test_claim_headers_in_encrypted_mail(account_maker):
        acc1, acc2 = account_maker(), account_maker()
        send_mail(acc1, acc2)
    
>       dec_msg = send_encrypted_mail(acc2, acc1)[1].dec_msg
tests/test_functional.py:25: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_functional.py:96: in send_encrypted_mail
    enc_msg = sender.encrypt_mime(msg, [r.addr for r in recipients]).enc_msg
.tox/py27/src/muacrypt/muacrypt/account.py:436: in encrypt_mime
    _account=self,
.tox/py27/local/lib/python2.7/site-packages/pluggy/__init__.py:617: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
.tox/py27/local/lib/python2.7/site-packages/pluggy/__init__.py:222: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
.tox/py27/local/lib/python2.7/site-packages/pluggy/__init__.py:216: in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
.tox/py27/local/lib/python2.7/site-packages/muacryptcc/plugin.py:71: in process_before_encryption
    self.commit_to_chain()
.tox/py27/local/lib/python2.7/site-packages/muacryptcc/plugin.py:144: in commit_to_chain
    self.head = self.state.commit(chain)
.tox/py27/src/claimchain/claimchain/state.py:129: in commit
    tree = _build_tree(tree_store, enc_items_map)
.tox/py27/src/claimchain/claimchain/utils/profiling.py:37: in wrapped
    return func(*args, **kwargs)
.tox/py27/src/claimchain/claimchain/state.py:68: in _build_tree
    store = ObjectStore(store)
.tox/py27/src/claimchain/claimchain/utils/wrappers.py:38: in __init__
    _check_hash(lookup_key, value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
key = '\x89\xa0\x02\xef\x16\x12!\xa5\xee\xcf\xdd\xaac\xae6\xff\xb1K!)\xa4\xafgj\xa3\x82\x92\x1e\xc1n\xa5\xf2'
value = <hippiehug.Chain.Block instance at 0x7fe1ef02d518>
    def _check_hash(key, value):
        if value.hid != key:
>           raise ValueError('Hash of the value is not the lookup key')
E           ValueError: Hash of the value is not the lookup key

```

We saw similar issues before gdanezis/rousseau-chain#5

**Comment by azul** [comment]
Looks like that failure is non deterministic too.

**Comment by hpk42** [comment]
looks good!

**Pull request merged**
